### ISSUE TITLE
Missing Nuget

### ISSUE THREAD

**Issue by varyamereon** [dmariogatto/Maui.Controls.BetterMaps#6]
Hi @dmariogatto ,

I'm converting my project from Xamarin and noticed that the NuGet Package is missing for this library. Could you make it available again?

Many thanks!

**Comment by dmariogatto** [comment]
@varyamereon 

[Here you go](https://www.nuget.org/packages/BetterMaps.Maui). Enjoy!

**Comment by varyamereon** [comment]
Very nice, thank you!!
